# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 02:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_slider', serialize=False, to='cms.CMSPlugin')),
                ('text1', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Please supply an text for the second slide')),
                ('image1', filer.fields.image.FilerImageField(help_text='Please supply an image for the first slide', on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
