# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 04:32
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='title1',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Please supply an title for the first slide'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text1',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Please supply an description for the first slide'),
        ),
    ]
