# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('app', '0002_auto_20190320_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', filer.fields.image.FilerImageField(help_text='Please supply an image for this slide', on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Text_Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Please supply an description for the item')),
                ('top', models.IntegerField(default=0)),
                ('left', models.IntegerField(default=0)),
                ('font_size', models.PositiveIntegerField(default=0)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Slide')),
            ],
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title1',
        ),
        migrations.AddField(
            model_name='slider',
            name='nav_buttons',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Slider'),
        ),
    ]
