# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190321_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text_slide',
            name='slide',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='image1',
            new_name='image',
        ),
        migrations.AddField(
            model_name='slide',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is active this slide?'),
        ),
        migrations.AddField(
            model_name='slide',
            name='left_text',
            field=models.IntegerField(blank=True, default=0, help_text='Left position description', null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='left_title',
            field=models.IntegerField(blank=True, default=0, help_text='Left position title', null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='show_button',
            field=models.BooleanField(default=True, help_text='Show button for this slide?'),
        ),
        migrations.AddField(
            model_name='slide',
            name='size_text',
            field=models.PositiveIntegerField(blank=True, default=50, help_text='Font size description', null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='size_title',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='Font size title', null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='text',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Please supply a description for the slide', null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='title',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default='Slide', help_text='Please supply a title for the slide', null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='top_text',
            field=models.IntegerField(blank=True, default=0, help_text='Top position description', null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='top_title',
            field=models.IntegerField(blank=True, default=0, help_text='Top position title', null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='url_button',
            field=models.CharField(blank=True, default='#', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Text_Slide',
        ),
    ]
