# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190321_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Position Slide', null=True),
        ),
    ]
