# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_slide_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='left_text',
            field=models.IntegerField(blank=True, default=0, help_text='Left position description', null=True, verbose_name='Left'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='left_title',
            field=models.IntegerField(blank=True, default=0, help_text='Left position title', null=True, verbose_name='Left'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='size_text',
            field=models.PositiveIntegerField(blank=True, default=50, help_text='Font size description', null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='size_title',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='Font size title', null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='top_text',
            field=models.IntegerField(blank=True, default=0, help_text='Top position description', null=True, verbose_name='Top'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='top_title',
            field=models.IntegerField(blank=True, default=0, help_text='Top position title', null=True, verbose_name='Top'),
        ),
    ]
