# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 01:24
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190321_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Please supply a title for the slide', null=True),
        ),
    ]
