# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('app', '0008_slide_text_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderActive',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='app_slideractive', to='cms.CMSPlugin')),
                ('id_slider', models.PositiveIntegerField(help_text='ID Slider', primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
