# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('app', '0009_slideractive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='slider',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='slideractive',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.DeleteModel(
            name='SliderActive',
        ),
    ]
