# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 02:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0020_old_tree_cleanup'),
        ('app', '0010_auto_20190321_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Please supply a title for the slide', null=True)),
                ('top_title', models.IntegerField(blank=True, default=0, help_text='Top position title', null=True, verbose_name='Top')),
                ('left_title', models.IntegerField(blank=True, default=0, help_text='Left position title', null=True, verbose_name='Left')),
                ('size_title', models.PositiveIntegerField(blank=True, default=100, help_text='Font size title', null=True, verbose_name='Size')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Please supply a description for the slide', null=True)),
                ('top_text', models.IntegerField(blank=True, default=0, help_text='Top position description', null=True, verbose_name='Top')),
                ('left_text', models.IntegerField(blank=True, default=0, help_text='Left position description', null=True, verbose_name='Left')),
                ('size_text', models.PositiveIntegerField(blank=True, default=50, help_text='Font size description', null=True, verbose_name='Size')),
                ('show_button', models.BooleanField(default=True, help_text='Show button for this slide?')),
                ('text_button', models.CharField(blank=True, max_length=255, null=True)),
                ('url_button', models.CharField(blank=True, default='#', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is active this slide?')),
                ('position', models.PositiveIntegerField(blank=True, default=0, help_text='Position Slide', null=True)),
                ('image', filer.fields.image.FilerImageField(help_text='Please supply an image for this slide', on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nav_buttons', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SliderActive',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_slideractive', serialize=False, to='cms.CMSPlugin')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Slider')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='slide',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Slider'),
        ),
    ]
