# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190321_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='left_button',
            field=models.IntegerField(blank=True, default=0, help_text='Left position button', null=True, verbose_name='Left'),
        ),
        migrations.AddField(
            model_name='slide',
            name='top_button',
            field=models.IntegerField(blank=True, default=0, help_text='Top position button', null=True, verbose_name='Top'),
        ),
    ]
