# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-23 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190322_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='left_button',
            field=models.IntegerField(blank=True, default=50, help_text='Left position', null=True, verbose_name='Left'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='left_text',
            field=models.IntegerField(blank=True, default=0, help_text='Left position', null=True, verbose_name='Left'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='left_title',
            field=models.IntegerField(blank=True, default=0, help_text='Left position', null=True, verbose_name='Left'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='show_button',
            field=models.BooleanField(default=True, help_text='Show button for this slide?', verbose_name='Show'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='size_text',
            field=models.PositiveIntegerField(blank=True, default=50, help_text='Font size', null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='size_title',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='Font size', null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='text',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Please supply a description for the slide', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='slide',
            name='text_button',
            field=models.CharField(blank=True, default='Show More', max_length=255, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Please supply a title for the slide', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='slide',
            name='top_button',
            field=models.IntegerField(blank=True, default=500, help_text='Top position', null=True, verbose_name='Top'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='top_text',
            field=models.IntegerField(blank=True, default=0, help_text='Top position', null=True, verbose_name='Top'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='top_title',
            field=models.IntegerField(blank=True, default=0, help_text='Top position', null=True, verbose_name='Top'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='url_button',
            field=models.CharField(blank=True, default='#', max_length=255, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='slideractive',
            name='nav_buttons',
            field=models.BooleanField(default=True, help_text='Enable low controls?', verbose_name='Low Controls'),
        ),
    ]
