# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-23 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190322_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideractive',
            options={'verbose_name': 'Slider'},
        ),
    ]
