# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-23 16:58
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190323_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='color_button',
        ),
        migrations.AddField(
            model_name='slide',
            name='color_background_button',
            field=colorfield.fields.ColorField(default='#FFF', max_length=18, verbose_name='Color Background'),
        ),
        migrations.AddField(
            model_name='slide',
            name='color_hover_button',
            field=colorfield.fields.ColorField(default='#58cf90', max_length=18, verbose_name='Color Hover'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='color_text',
            field=colorfield.fields.ColorField(default='#FFF', max_length=18, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='color_title',
            field=colorfield.fields.ColorField(default='#FFF', max_length=18, verbose_name='Color'),
        ),
    ]
