# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-23 23:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('app', '0021_auto_20190323_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('position', models.DecimalField(decimal_places=1, default=0, help_text='Position partner on slide', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Is active this partner?')),
                ('image', filer.fields.image.FilerImageField(help_text='Please supply an image of this partner', on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name_plural': 'partners',
            },
        ),
    ]
