# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-24 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
