# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-24 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20190324_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='url',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
